[book]
authors = ["Ivan Elfimov <ielfimov@gmail.com>"]
language = "ru"
multilingual = true
src = "src"
title = "Ansible для начинающих"
git-repository-url = "https://github.com/biozz/ansible-tutorial"
